[package]
name = "pev"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true, optional = true }
ucf-protocol = { path = "../ucf-protocol" }
limits = { path = "../crates/limits" }
