[package]
name = "profiles"
version = "0.1.0"
edition.workspace = true

[dependencies]
engine = { path = "../engine" }
pvgs_client = { path = "../pvgs_client" }
rsv = { path = "../rsv" }
ucf-protocol = { path = "../ucf-protocol" }
