[package]
name = "gem"
version = "0.1.0"
edition.workspace = true

[dependencies]
hex = "0.4"
pvgs_client = { path = "../pvgs_client" }
thiserror.workspace = true
ucf-protocol = { path = "../ucf-protocol" }
prost.workspace = true

[dev-dependencies]
once_cell = "1"
