[package]
name = "ucf-protocol"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
prost = { workspace = true }

[features]
default = []
serde = ["dep:serde"]
